$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

type: pipeline

display_name: daily-batch-inference

settings:
  default_compute: azureml:aml-cluster-private

jobs:

  inference_job:

    type: command

    component: file:./inference-component.yml

    inputs:

      model:
        type: mlflow_model
        path: azureml:my_production_model:1